name: rpgems

services:
  frontend:
    image: nginx:1.27-alpine3.20
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=rpgems
      - NGINX_PORT=80
    networks:
      - frontend-connection

  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - path: "./.env"
        required: true
    ports:
      - "80:80"
    networks:
      - database-backend-connection
      - frontend-connection

  database:
    image: postgres:16.4-alpine3.20
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: rpgems
    networks:
      - database-backend-connection

networks:
  frontend-connection:
    driver: bridge
  database-backend-connection:
    driver: bridge
    internal: true